package com.evya.myweatherapp.ui

enum class AttractionEnum (val attraction: String, val attractionKey: String) {
    AlpineHuts("Alpine huts", "alpine_hut"),
    LoveHotels("Love hotels", "love_hotels"),
    VillasAndChalet("Villas and chalet", "villas_and_chalet"),
    Hostels("Hostels","hostels"),
    Hotels ("Hotels","other_hotels"),
    Motels ("Motels", "motels"),
    Resorts ("Resorts","resorts"),
    Campsites ("Campsites", "campsites"),
    GuestHouses ("Guest houses", "guest_houses"),
    Apartments ("Apartments", "apartments"),
    Accomodations ("Accomodations", "accomodations"),
    BureauDeChange ("Bureau de change","bureau_de_change"),
 /*   ATM (atm)
    Banks (bank)
    Banks (banks)
    Picnic sites (picnic_site)
    Biergartens (biergartens)
    Bars (bars)
    Pubs (pubs)
    Food courts (food_courts)
    Fast food (fast_food)
    Cafes (cafes)
    Restaurants (restaurants)
    Foods (foods)
    Bakeries (bakeries)
    Marketplaces (marketplaces)
    Malls (malls)
    Outdoor (outdoor)
    Fish stores (fish_stores)
    Conveniences (conveniences)
    Supermarkets (supermarkets)
    Shops (shops)
    Fuel (fuel)
    Boat sharing (boat_sharing)
    Bicycle rental (bicycle_rental)
    Charging stations (charging_station)
    Car wash (car_wash)
    Car sharing (car_sharing)
    Car rental (car_rental)
    Transport (transport)
    Tourist facilities (tourist_facilities)
    hookah (hookah)
    erotic shops (erotic_shops)
    love hotels (adult_hotels)
    alcohol (alcohol)
    nightclubs (nightclubs)
    brothels (brothels)
    casino (casino)
    strip clubs (strip_clubs)
    Adult (adult)
    pools (pools)
    stadiums (stadiums)
    kitesurfing (kitesurfing)
    surfing (surfing)
    climbing (climbing)
    wrecks (wrecks)
    dive spots (dive_spots)
    dive centers (dive_centers)
    diving (diving)
    other winter sports (other_winter_sports)
    cross country skiing (cross_country_skiing)
    skiing (skiing)
    winter sport (winter_sports)
    Sport (sport)
    bathhouses (other_bathhouses)
    open-air baths (open_air_baths)
    thermal baths (thermal_baths)
    sauns (saunas)
    baths and saunas (baths_and_saunas)
    other amusement rides (other_amusement_rides)
    ferris wheels (ferris_wheels)
    roller coasters (roller_coasters)
    water parks (water_parks)
    miniature parks (miniature_parks)
    amusement parks (amusement_parks)
    Amusements (amusements)
    historic attractions (historic_object)
    tourist attractions (tourist_object)
    unclassified attractions (unclassified_objects)
    Red telephone boxes (red_telephone_boxes)
    View points (view_points)
    Sundials (sundials)
    Other (other)
    Other buildings (other_buildings)
    Mineshafts (mineshafts)
    Abandoned mineshafts (abandoned_mineshafts)
    Abandoned railway stations (abandoned_railway_stations)
    Mills (mills)
    Dams (dams)
    Power stations (power_stations)
    Mints (mints)
    Factories (factories)
    Railway stations (railway_stations)
    Industrial facilities (industrial_facilities)
    Lighthouses (lighthouses)
    other towers (other_towers)
    minarets (minarets)
    bell towers (bell_towers)
    clock towers (clock_towers)
    transmitter towers (transmitter_towers)
    water towers (water_towers)
    watchtowers (watchtowers)
    observation towers (observation_towers)
    Towers (towers)
    other bridges (other_bridges)
    suspension bridges (suspension_bridges)
    aqueducts (aqueducts)
    footbridges (footbridges)
    Roman bridges (roman_bridges)
    viaducts (viaducts)
    stone bridges (stone_bridges)
    moveable bridges (moveable_bridges)
    Bridges (bridges)
    Skyscrapers (skyscrapers)
    destroyed objects (destroyed_objects)
    buildings and structures (other_buildings_and_structures)
    farms (farms)
    wineries (wineries)
    manor houses (manor_houses)
    palaces (palaces)
    triumphal archs (triumphal_archs)
    amphitheatres (amphitheatres)
    pyramids (pyramids)
    Historic architecture (historic_architecture)
    Architecture (architecture)
    monasteries (monasteries)
    other temples (other_temples)
    egyptian temples (egyptian_temples)
    hindu temples (hindu_temples)
    buddhist temples (buddhist_temples)
    synagogues (synagogues)
    mosques (mosques)
    cathedrals (cathedrals)
    other churches (other_churches)
    catholic churches (catholic_churches)
    eastern orthodox churches (eastern_orthodox_churches)
    churches (churches)
    Religion (religion)
    other burial places (other_burial_places)
    crypts (crypts)
    war memorials (war_memorials)
    mausoleums (mausoleums)
    tumuluses (tumuluses)
    dolmens (dolmens)
    necropolises (necropolises)
    war graves (war_graves)
    cemeteries (cemeteries)
    Burial places (burial_places)
    archaeological sites (other_archaeological_sites)
    rune stones (rune_stones)
    settlements (settlements)
    cave paintings (cave_paintings)
    roman villas (roman_villas)
    menhirs (menhirs)
    megaliths (megaliths)
    Archaeology (archaeology)
    monuments (monuments)
    milestones (milestones)
    Monuments and memorials (monuments_and_memorials)
    other fortifications (other_fortifications)
    kremlins (kremlins)
    bunkers (bunkers)
    defensive walls (defensive_walls)
    fortified towers (fortified_towers)
    hillforts (hillforts)
    castles (castles)
    Fortifications (fortifications)
    battlefields (battlefields)
    fishing villages (fishing_villages)
    historic settlements (historic_settlements)
    historic districts (historic_districts)
    Historical places (historical_places)
    Historical (historic)
    sculptures (sculptures)
    fountains (fountains)
    gardens and parks (gardens_and_parks)
    installation (installation)
    squares and streets (squares)
    wall painting (wall_painting)
    Urban environment (urban_environment)
    circuses (circuses)
    movie theatres (cinemas)
    other theatres (other_theatres)
    сhildren's theatres (children_theatres)
    puppetries (puppetries)
    concert halls (concert_halls)
    music venues (music_venues)
    opera houses (opera_houses)
    sylvan theatres (sylvan_theatres)
    Theaters and entertainments (theatres_and_entertainments)
    other museums (other_museums)
    aquariums (aquariums)
    zoos (zoos)
    art galleries (art_galleries)
    historic house museums (historic_house_museums)
    children museums (children_museums)
    fashion museums (fashion_museums)
    open-air museums (open_air_museums)
    biographical museums (biographical_museums)
    archaeological museums (archaeological_museums)
    history museums (history_museums)
    military museums (military_museums)
    planetariums (planetariums)
    science museums (science_museums)
    other technology museums (other_technology_museums)
    heritage railways (heritage_railways)
    computer museums (computer_museums)
    automobile museums (automobile_museums)
    aviation museums (aviation_museums)
    railway museums (railway_museums)
    maritime museums (maritime_museums)
    museums of science and technology (museums_of_science_and_technology)
    local museums (local_museums)
    national museums (national_museums)
    Museums (museums)
    Cultural (cultural)
    Glaciers (glaciers)
    nature conservation areas (other_nature_conservation_areas)
    natural monuments (natural_monuments)
    other nature reserves (nature_reserves_others)
    national parks (national_parks)
    wildlife reserves (wildlife_reserves)
    aquatic protected areas (aquatic_protected_areas)
    Nature reserves (nature_reserves)
    other beaches (other_beaches)
    nude beaches (nude_beaches)
    urbans beaches (urbans_beaches)
    rocks beaches (rocks_beaches)
    shingle beaches (shingle_beaches)
    black sand beaches (black_sand_beaches)
    white sand beaches (white_sand_beaches)
    golden sand beaches (golden_sand_beaches)
    Beaches (beaches)
    other lakes (other_lakes)
    lagoons (lagoons)
    waterfalls (waterfalls)
    canals (canals)
    rivers (rivers)
    reservoirs (reservoirs)
    dry lakes (dry_lakes)
    salt lakes (salt_lakes)
    rift lakes (rift_lakes)
    crater lakes (crater_lakes)
    Water (water)
    rock formations (rock_formations)
    canyons (canyons)
    caves (caves)
    volcanoes (volcanoes)
    mountain peaks (mountain_peaks)
    Geological formations (geological_formations)
    other springs (springs_others)
    geysers (geysers)
    hot springs (hot_springs)
    Natural springs (natural_springs)
    other islands (other_islands)
    high islands (high_islands)
    desert islands (desert_islands)
    coral islands (coral_islands)
    inland islands (inland_islands)
    tidal islands (tidal_islands)
    Islands (islands)
    Natural (natural)
    Interesting places (interesting_places)*/
}