package com.evya.myweatherapp.firebaseanalytics

enum class FireBaseEventsNamesStrings(val eventName: String) {
    CHOOSE_CITY_FROM_TOP_ADAPTER("choose_city_from_top_adapter"),
    CHOOSE_CITY_FROM_FAVORITES("choose_city_from_favorites"),
    DELETE_CITY_FROM_FAVORITES("delete_city_from_favorites"),
    DELETE_ALL_CITIES_FROM_FAVORITES("delete_all_cities_from_favorites"),
    NAVIGATE_TO_WEATHER("navigate_to_weather"),
    CHANGE_TEMP_UNITS("change_temp_units"),
    NAVIGATE_TO_GOOGLE_MAP("navigate_to_google_map"),
    SEARCH_IN_GOOGLE_MAP("search_in_google_map"),
    SHOW_WEATHER("show_weather"),
    NAVIGATE_TO_ATTRACTIONS("navigate_to_attractions"),
    NAVIGATE_TO_FAVORITES("navigate_to_favorites"),
    NAVIGATE_TO_SHOW_INFO("navigate_to_show_info"),
    SEARCH_ATTRACTIONS("search_attractions"),
    WHAT_TO_DO("what_to_do"),
    CLICK_ON_BANNER_AD("click_on_banner_ad"),
    ON_BANNER_AD_FAILED_TO_LOAD("on_banner_ad_failed_to_load"),
    ON_BANNER_AD_IMPRESSION("on_banner_ad_impression"),
    ON_INTERSTITIAL_AD_LOADED("on_interstitial_ad_loaded"),
    ON_INTERSTITIAL_AD_FAILED_TO_LOAD("on_interstitial_ad_failed_to_load"),
    CLICK_ON_INTERSTITIAL_AD("click_on_interstitial_ad"),
    ON_INTERSTITIAL_AD_DISMISSED_FULL_SCREEN_CONTENT("on_interstitial_ad_dismissed_full_screen_content"),
    ON_INTERSTITIAL_AD_FAILED_TO_SHOW_FULL_SCREEN_CONTENT("on_interstitial_ad_failed_to_show_full_screen_content"),
    ON_INTERSTITIAL_AD_IMPRESSION("on_interstitial_ad_impression"),
    ON_INTERSTITIAL_AD_SHOWED_FULL_SCREEN_CONTENT("on_interstitial_ad_showed_full_screen_content"),
    SHOW_ALERT("show_alert"),
}